### ISSUE TITLE
Assign Fling action to Tasker Task - Fails

### ISSUE THREAD

**Issue by zhdenny** [DirtyUnicorns/android_packages_apps_DUI#1]
As the title says.......Fling seems to NOT like it when you assign a Tasker Shortcut Task to any Fling Action. It just plain doesn't work. I've seen this before with other apps and the Devs were always able to fix it but I do not know the specifics on how.

Just reporting the issue. Thanks

**Comment by BoredOutOfMyGit** [comment]
Use JIRA to report issues.
